{
 "title": "Linode Regions CO2 Dashboard Overview",
 "description": "Linode Regions CO2 Dashboard ",
 "time": { "from": "now-24h", "to": "now" },
 "panels": [
  {
   "title": "Atlanta us-southeast",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 5, "x": 0, "y": 0 },
   "targets": [
    {
     "query": "from(bucket: \"us-southeast\")\n  |> range(start: -30d)\n  |> filter(fn: (r) => r._measurement == \"co2_intensity\")\n  |> filter(fn: (r) => r.location == \"Southern Company Services\")\n  |> filter(fn: (r) => r._field == \"value\")\n  |> aggregateWindow(every: 5m, fn: mean, createEmpty: false)\n  |> yield(name: \"mean\")"
    }
   ]
  },
  {
   "title": "Atlanta us-southeast",
   "type": "histogram",
   "gridPos": { "h": 10, "w": 5, "x": 5, "y": 0 },
   "targets": [
    {
     "query": "from(bucket: \"us-southeast\")\n  |> range(start: -30d)\n  |> filter(fn: (r) => r._measurement == \"co2_intensity\")\n  |> filter(fn: (r) => r.location == \"Southern Company Services\")\n  |> filter(fn: (r) => r._field == \"value\")\n  |> aggregateWindow(every: 5m, fn: mean, createEmpty: false)\n  |> yield(name: \"mean\")"
    }
   ]
  },
  {
   "title": "Atlanta Average CO2 Emissions (last 30 days)",
   "type": "stat",
   "gridPos": { "h": 10, "w": 6, "x": 10, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "\nfrom(bucket: \"us-southeast\")\n  |> range(start: -30d)  // Get all data over the last 30 days\n  |> filter(fn: (r) => r._measurement == \"co2_intensity\")\n  |> filter(fn: (r) => r._field == \"value\")\n  |> group()  // Group all data together (remove any subgrouping)\n  |> stddev(column: \"_value\")  // Calculate the standard deviation for the entire dataset\n  |> map(fn: (r) => ({\n      r with three_sigma: r._value * 3.0  // Multiply standard deviation by 3 to get 3-sigma\n  }))\n  |> keep(columns: [\"three_sigma\"])  // Only keep the 3-sigma value\n  |> yield(name: \"three_sigma\")\n\nfrom(bucket: \"us-southeast\")\n  |> range(start: -30d)  // Get data for the last 30 days\n  |> filter(fn: (r) => r._measurement == \"co2_intensity\")\n  |> filter(fn: (r) => r._field == \"value\")\n  |> aggregateWindow(every: 1d, fn: mean, createEmpty: false)  // Aggregate data by day\n  |> group()\n  |> mean(column: \"_value\")  // Calculate the mean CO2 intensity for the last 30 days\n  |> yield(name: \"30_day_average\")\n\n"
    }
   ]
  },
  {
   "title": "Atlanta us-southeast CO2 Emissions (gCO2e  per kWh)",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 8, "x": 16, "y": 0 },
   "targets": [
    {
     "query": "from(bucket: \"us-southeast\")\n  |> range(start: -30d)  // Adjust time range as needed\n  |> filter(fn: (r) => r._measurement == \"co2_intensity\")\n  |> filter(fn: (r) => r._field == \"value\")\n  |> aggregateWindow(every: 5m, fn: mean, createEmpty: false)  // Aggregate by 5-minute intervals\n  |> yield(name: \"mean\")"
    }
   ]
  },
  {
   "title": "London eu-west",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 5, "x": 0, "y": 10 },
   "targets": [
    {
     "query": "from(bucket: \"eu-west\")\n  |> range(start: -30d)  // Adjust time range as needed\n  |> filter(fn: (r) => r._measurement == \"co2_intensity\")\n  |> filter(fn: (r) => r._field == \"value\")\n  |> aggregateWindow(every: 5m, fn: mean, createEmpty: false)  // Aggregate by 5-minute intervals\n  |> yield(name: \"mean\")"
    }
   ]
  },
  {
   "title": "London eu-west",
   "type": "histogram",
   "gridPos": { "h": 11, "w": 5, "x": 5, "y": 10 },
   "targets": [
    {
     "query": "from(bucket: \"eu-west\")\n  |> range(start: -30d)  // Adjust time range as needed\n  |> filter(fn: (r) => r._measurement == \"co2_intensity\")\n  |> filter(fn: (r) => r._field == \"value\")\n  |> aggregateWindow(every: 5m, fn: mean, createEmpty: false)  // Aggregate by 5-minute intervals\n  |> yield(name: \"mean\")"
    }
   ]
  },
  {
   "title": "London Average CO2 Emissions (last 30 days)",
   "type": "stat",
   "gridPos": { "h": 11, "w": 6, "x": 10, "y": 10 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"eu-west\")\n  |> range(start: -30d)  // Get data for the last 30 days\n  |> filter(fn: (r) => r._measurement == \"co2_intensity\")\n  |> filter(fn: (r) => r._field == \"value\")\n  |> aggregateWindow(every: 1d, fn: mean, createEmpty: false)  // Aggregate data by day\n  |> group()\n  |> mean(column: \"_value\")  // Calculate the mean CO2 intensity for the last 30 days\n  |> yield(name: \"30_day_average\")\n\nfrom(bucket: \"eu-west\")\n  |> range(start: -30d)  // Get all data over the last 30 days\n  |> filter(fn: (r) => r._measurement == \"co2_intensity\")\n  |> filter(fn: (r) => r._field == \"value\")\n  |> group()  // Group all data together (remove any subgrouping)\n  |> stddev(column: \"_value\")  // Calculate the standard deviation for the entire dataset\n  |> map(fn: (r) => ({\n      r with three_sigma: r._value * 3.0  // Multiply standard deviation by 3 to get 3-sigma\n  }))\n  |> keep(columns: [\"three_sigma\"])  // Only keep the 3-sigma value\n  |> yield(name: \"three_sigma\")\n"
    }
   ]
  },
  {
   "title": "London eu-west CO2 Emissions (gCO2e per kWh)",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 8, "x": 16, "y": 10 },
   "targets": [
    {
     "query": "from(bucket: \"eu-west\")\n  |> range(start: -30d)  // Adjust time range as needed\n  |> filter(fn: (r) => r._measurement == \"co2_intensity\")\n  |> filter(fn: (r) => r._field == \"value\")\n  |> aggregateWindow(every: 5m, fn: mean, createEmpty: false)  // Aggregate by 5-minute intervals\n  |> yield(name: \"mean\")"
    }
   ]
  },
  {
   "title": "Dallas us-central",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 5, "x": 0, "y": 21 },
   "targets": [
    {
     "query": "from(bucket: \"us-central\")\n  |> range(start: -30d)\n  |> filter(fn: (r) => r._measurement == \"co2_intensity\")\n  |> filter(fn: (r) => r.location == \"Electric Reliability Council of Texas\")\n  |> filter(fn: (r) => r._field == \"value\")\n  |> aggregateWindow(every: 5m, fn: mean, createEmpty: false)\n  |> yield(name: \"mean\")"
    }
   ]
  },
  {
   "title": "Dallas us-central",
   "type": "histogram",
   "gridPos": { "h": 9, "w": 5, "x": 5, "y": 21 },
   "targets": [
    {
     "query": "from(bucket: \"us-central\")\n  |> range(start: -30d)\n  |> filter(fn: (r) => r._measurement == \"co2_intensity\")\n  |> filter(fn: (r) => r.location == \"Electric Reliability Council of Texas\")\n  |> filter(fn: (r) => r._field == \"value\")\n  |> aggregateWindow(every: 5m, fn: mean, createEmpty: false)\n  |> yield(name: \"mean\")"
    }
   ]
  },
  {
   "title": "Dallas Average CO2 Emissions (last 30 days)",
   "type": "stat",
   "gridPos": { "h": 9, "w": 6, "x": 10, "y": 21 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"us-central\")\n  |> range(start: -30d)  // Get data for the last 30 days\n  |> filter(fn: (r) => r._measurement == \"co2_intensity\")\n  |> filter(fn: (r) => r._field == \"value\")\n  |> aggregateWindow(every: 1d, fn: mean, createEmpty: false)  // Aggregate data by day\n  |> group()\n  |> mean(column: \"_value\")  // Calculate the mean CO2 intensity for the last 30 days\n  |> yield(name: \"30_day_average\")\n\nfrom(bucket: \"us-central\")\n  |> range(start: -30d)  // Get all data over the last 30 days\n  |> filter(fn: (r) => r._measurement == \"co2_intensity\")\n  |> filter(fn: (r) => r._field == \"value\")\n  |> group()  // Group all data together (remove any subgrouping)\n  |> stddev(column: \"_value\")  // Calculate the standard deviation for the entire dataset\n  |> map(fn: (r) => ({\n      r with three_sigma: r._value * 3.0  // Multiply standard deviation by 3 to get 3-sigma\n  }))\n  |> keep(columns: [\"three_sigma\"])  // Only keep the 3-sigma value\n  |> yield(name: \"three_sigma\")\n"
    }
   ]
  },
  {
   "title": "Dallas us-southeast CO2 Emissions (gCO2e per kWh)",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 8, "x": 16, "y": 21 },
   "targets": [
    {
     "query": "from(bucket: \"us-central\")\n  |> range(start: -30d)  // Adjust time range as needed\n  |> filter(fn: (r) => r._measurement == \"co2_intensity\")\n  |> filter(fn: (r) => r._field == \"value\")\n  |> aggregateWindow(every: 5m, fn: mean, createEmpty: false)  // Aggregate by 5-minute intervals\n  |> yield(name: \"mean\")"
    }
   ]
  },
  {
   "title": "Los Angeles CA us-lax",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 5, "x": 0, "y": 30 },
   "targets": [
    {
     "query": "from(bucket: \"us-lax\")\n  |> range(start: -30d)\n  |> filter(fn: (r) => r._measurement == \"co2_intensity\")\n  |> filter(fn: (r) => r.location == \"California ISO\")\n  |> filter(fn: (r) => r._field == \"value\")\n  |> aggregateWindow(every: 5m, fn: mean, createEmpty: false)\n  |> yield(name: \"mean\")"
    }
   ]
  },
  {
   "title": "Los Angeles CA us-lax",
   "type": "histogram",
   "gridPos": { "h": 8, "w": 5, "x": 5, "y": 30 },
   "targets": [
    {
     "query": "from(bucket: \"us-lax\")\n  |> range(start: -30d)\n  |> filter(fn: (r) => r._measurement == \"co2_intensity\")\n  |> filter(fn: (r) => r.location == \"California ISO\")\n  |> filter(fn: (r) => r._field == \"value\")\n  |> aggregateWindow(every: 5m, fn: mean, createEmpty: false)\n  |> yield(name: \"mean\")"
    }
   ]
  },
  {
   "title": "Los Angeles Average CO2 Emissions (last 30 days)",
   "type": "stat",
   "gridPos": { "h": 8, "w": 6, "x": 10, "y": 30 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"us-lax\")\n  |> range(start: -30d)  // Get data for the last 30 days\n  |> filter(fn: (r) => r._measurement == \"co2_intensity\")\n  |> filter(fn: (r) => r._field == \"value\")\n  |> aggregateWindow(every: 1d, fn: mean, createEmpty: false)  // Aggregate data by day\n  |> group()\n  |> mean(column: \"_value\")  // Calculate the mean CO2 intensity for the last 30 days\n  |> yield(name: \"30_day_average\")\n\nfrom(bucket: \"us-lax\")\n  |> range(start: -30d)  // Get all data over the last 30 days\n  |> filter(fn: (r) => r._measurement == \"co2_intensity\")\n  |> filter(fn: (r) => r._field == \"value\")\n  |> group()  // Group all data together (remove any subgrouping)\n  |> stddev(column: \"_value\")  // Calculate the standard deviation for the entire dataset\n  |> map(fn: (r) => ({\n      r with three_sigma: r._value * 3.0  // Multiply standard deviation by 3 to get 3-sigma\n  }))\n  |> keep(columns: [\"three_sigma\"])  // Only keep the 3-sigma value\n  |> yield(name: \"three_sigma\")\n"
    }
   ]
  },
  {
   "title": "Los Angeles CA us-lax CO2 Emissions (gCO2e  per kWh)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 30 },
   "targets": [
    {
     "query": "from(bucket: \"us-lax\")\n  |> range(start: -30d)  // Adjust time range as needed\n  |> filter(fn: (r) => r._measurement == \"co2_intensity\")\n  |> filter(fn: (r) => r._field == \"value\")\n  |> aggregateWindow(every: 5m, fn: mean, createEmpty: false)  // Aggregate by 5-minute intervals\n  |> yield(name: \"mean\")"
    }
   ]
  },
  {
   "title": "Newark NJ us-east (gCO2 per kWh)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 5, "x": 0, "y": 38 },
   "targets": [
    {
     "query": "from(bucket: \"us-east\")\n  |> range(start: -30d)\n  |> filter(fn: (r) => r._measurement == \"co2_intensity\")\n  |> filter(fn: (r) => r.location == \"PJM interconnection\")\n  |> filter(fn: (r) => r._field == \"value\")\n  |> aggregateWindow(every: 5m, fn: mean, createEmpty: false)\n  |> yield(name: \"mean\")"
    }
   ]
  },
  {
   "title": "Newark NJ us-east (gCO2 per kWh)",
   "type": "histogram",
   "gridPos": { "h": 8, "w": 5, "x": 5, "y": 38 },
   "targets": [
    {
     "query": "from(bucket: \"us-east\")\n  |> range(start: -30d)\n  |> filter(fn: (r) => r._measurement == \"co2_intensity\")\n  |> filter(fn: (r) => r._field == \"value\")\n  |> aggregateWindow(every: 5m, fn: mean, createEmpty: false)\n  |> yield(name: \"mean\")"
    }
   ]
  },
  {
   "title": "Newark NJ us-east (gCO2 per kWh)",
   "type": "stat",
   "gridPos": { "h": 8, "w": 6, "x": 10, "y": 38 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"us-east\")\n  |> range(start: -30d)  // Get data for the last 30 days\n  |> filter(fn: (r) => r._measurement == \"co2_intensity\")\n  |> filter(fn: (r) => r._field == \"value\")\n  |> aggregateWindow(every: 1d, fn: mean, createEmpty: false)  // Aggregate data by day\n  |> group()\n  |> mean(column: \"_value\")  // Calculate the mean CO2 intensity for the last 30 days\n  |> yield(name: \"30_day_average\")\n\nfrom(bucket: \"us-east\")\n  |> range(start: -30d)  // Get all data over the last 30 days\n  |> filter(fn: (r) => r._measurement == \"co2_intensity\")\n  |> filter(fn: (r) => r._field == \"value\")\n  |> group()  // Group all data together (remove any subgrouping)\n  |> stddev(column: \"_value\")  // Calculate the standard deviation for the entire dataset\n  |> map(fn: (r) => ({\n      r with three_sigma: r._value * 3.0  // Multiply standard deviation by 3 to get 3-sigma\n  }))\n  |> keep(columns: [\"three_sigma\"])  // Only keep the 3-sigma value\n  |> yield(name: \"three_sigma\")\n"
    }
   ]
  },
  {
   "title": "Newark NJ us-east (gCO2 per kWh)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 38 },
   "targets": [
    {
     "query": "from(bucket: \"us-east\")\n  |> range(start: -30d)  // Adjust time range as needed\n  |> filter(fn: (r) => r._measurement == \"co2_intensity\")\n  |> filter(fn: (r) => r._field == \"value\")\n  |> aggregateWindow(every: 5m, fn: mean, createEmpty: false)  // Aggregate by 5-minute intervals\n  |> yield(name: \"mean\")"
    }
   ]
  },
  {
   "title": "Paris fr-par",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 5, "x": 0, "y": 46 },
   "targets": [
    {
     "query": "from(bucket: \"fr-par\")\n  |> range(start: -30d)  // Adjust time range as needed\n  |> filter(fn: (r) => r._measurement == \"co2_intensity\")\n  |> filter(fn: (r) => r._field == \"value\")\n  |> aggregateWindow(every: 5m, fn: mean, createEmpty: false)  // Aggregate by 5-minute intervals\n  |> yield(name: \"mean\")"
    }
   ]
  },
  {
   "title": "Paris fr-par (gCO2 per kWh)",
   "type": "histogram",
   "gridPos": { "h": 8, "w": 5, "x": 5, "y": 46 },
   "targets": [
    {
     "query": "from(bucket: \"fr-par\")\n  |> range(start: -30d)\n  |> filter(fn: (r) => r._measurement == \"co2_intensity\")\n  |> filter(fn: (r) => r._field == \"value\")\n  |> aggregateWindow(every: 5m, fn: mean, createEmpty: false)\n  |> yield(name: \"mean\")"
    }
   ]
  },
  {
   "title": "Paris fr-par (gCO2 per kWh)",
   "type": "stat",
   "gridPos": { "h": 8, "w": 6, "x": 10, "y": 46 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"fr-par\")\n  |> range(start: -30d)  // Get data for the last 30 days\n  |> filter(fn: (r) => r._measurement == \"co2_intensity\")\n  |> filter(fn: (r) => r._field == \"value\")\n  |> aggregateWindow(every: 1d, fn: mean, createEmpty: false)  // Aggregate data by day\n  |> group()\n  |> mean(column: \"_value\")  // Calculate the mean CO2 intensity for the last 30 days\n  |> yield(name: \"30_day_average\")\n\nfrom(bucket: \"fr-par\")\n  |> range(start: -30d)  // Get all data over the last 30 days\n  |> filter(fn: (r) => r._measurement == \"co2_intensity\")\n  |> filter(fn: (r) => r._field == \"value\")\n  |> group()  // Group all data together (remove any subgrouping)\n  |> stddev(column: \"_value\")  // Calculate the standard deviation for the entire dataset\n  |> map(fn: (r) => ({\n      r with three_sigma: r._value * 3.0  // Multiply standard deviation by 3 to get 3-sigma\n  }))\n  |> keep(columns: [\"three_sigma\"])  // Only keep the 3-sigma value\n  |> yield(name: \"three_sigma\")\n"
    }
   ]
  },
  {
   "title": "Paris fr-par (gCO2 per kWh)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 46 },
   "targets": [
    {
     "query": "from(bucket: \"fr-par\")\n  |> range(start: -30d)  // Adjust time range as needed\n  |> filter(fn: (r) => r._measurement == \"co2_intensity\")\n  |> filter(fn: (r) => r._field == \"value\")\n  |> aggregateWindow(every: 5m, fn: mean, createEmpty: false)  // Aggregate by 5-minute intervals\n  |> yield(name: \"mean\")"
    }
   ]
  }
 ]
}